mksquashfs: limit the maximum cpiostyle filename to PATH_MAX
Previously get_filename_from_stdin() did not place an upper bound
on the maximum length of filename read in from stdin.  That could
have allowed a malicious user to pipe in an extremely long filename
which could cause Mksquashfs to run out of memory.

This commit limits the maximum filename to PATH_MAX.

After this commit, piping a too long name will cause Mksquashfs to
abort

phillip@phoenix:/tmp$ cat big-filename | mksquashfs - output -cpiostyle
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on output, block size 131072.
FATAL ERROR: Cpiostyle input filename exceeds maximum path limit of 4096
bytes!

Cpio also doesn't appear to limit the input filename to PATH_MAX

phillip@phoenix:/tmp/test2$ cat big-filename | cpio -o > /dev/null
[ FILENAME OUTPUT LINES DELETED ]
Cannot stat: File name too long
1 block

The above error being caused by Cpio passing a pathname exceeding PATH_MAX
to the stat() system call.

Signed-off-by: Phillip Lougher <phillip@squashfs.org.uk>