sqfstar: add new -pseudo-dir option that automatically creates leading dirs
Originally if you created a Pseudo file with a pathname with leading
directories that were missing, it would be ignored.  This has now been
hardened so that any missing directories are now treated as fatal.

However it could be convienient for a pre-defined directory to used in
cases where a directory is missing, rather than abort the build.

This is the best of both worlds, pseudo file definitions will now be
created without having to ensure the leading directories are always
present in the filesystem.

e.g. the following failure

$ sqfstar -p "/dir1/dir2/dir3/dir4/file f 0444 0 0 echo hello" z < /dev/null
Creating 4.0 filesystem on z, block size 131072.
FATAL ERROR: Pathname "dir1" does not exist in filesystem.  Some pseudo definitions will not be created.

will be prevented with the -pseudo-dir (or -pd for short) option

$ sqfstar -pd "d 0444 phillip phillip" -p "/dir1/dir2/dir3/dir4/file f 0444 0 0 echo hello" -quiet z < /dev/null
phillip@phoenix:/tmp$ unsquashfs -lls z
drwxrwxrwx phillip/phillip          27 2024-04-10 21:01 squashfs-root
dr--r--r-- phillip/phillip          27 2024-04-10 21:01 squashfs-root/dir1
dr--r--r-- phillip/phillip          27 2024-04-10 21:01 squashfs-root/dir1/dir2
dr--r--r-- phillip/phillip          27 2024-04-10 21:01 squashfs-root/dir1/dir2/dir3
dr--r--r-- phillip/phillip          27 2024-04-10 21:01 squashfs-root/dir1/dir2/dir3/dir4
-r--r--r-- root/root                 6 2024-04-10 21:01 squashfs-root/dir1/dir2/dir3/dir4/file

Signed-off-by: Phillip Lougher <phillip@squashfs.org.uk>