Unsquashfs: don't chmod() directory not owned by user running Unsquashfs
If using the -force option and a directory already exists, Unsquashfs
will always try to change the permissions to u=rwx (User can read, write
and search).

But, if the directory isn't owned by the user running Unsquashfs, the
chmod() system call will fail, leading to Unsquashfs giving a FATAL
ERROR similar to:

----
Parallel unsquashfs: Using 4 processors
4 inodes (4 blocks) to write

FATAL ERROR: dir_scan: failed to change permissions for directory
squashfs-root/dir, because Operation not permitted
----

This commit changes the code so it will only chmod() on a directory
owned by the user running Unsquashfs, and only then if it has insuffient
permissions to descend into it.

For directories owned by others it will check to see if it has
sufficient existing permissions to descend into it.

Fixes issue https://github.com/plougher/squashfs-tools/issues/385

Signed-off-by: Phillip Lougher <phillip@squashfs.org.uk>