print_pager: add missing includes
When building with musl:

  print_pager.h:33:25: error: unknown type name 'pid_t'
     33 | extern void wait_to_die(pid_t process);
        |                         ^~~~~
  print_pager.h:34:25: error: unknown type name 'pid_t'
     34 | extern FILE *exec_pager(pid_t *process);
        |                         ^~~~~

print_pager.h uses pid_t and FILE, so add the required #includes to
ensure that these are defined.

Signed-off-by: Ross Burton <ross.burton@arm.com>