thread: add the missing pthread.h header
Fix build error on macos:

In file included from mksquashfs_help.c:35:
./thread.h:46:39: error: unknown type name 'pthread_mutex_t'; did you mean 'pthread_attr_t'?
   46 | extern void wait_thread_idle(int tid, pthread_mutex_t *mutex);
      |                                       ^~~~~~~~~~~~~~~
      |                                       pthread_attr_t

Signed-off-by: Shiji Yang <yangshiji66@outlook.com>