Need to include unistd.h before using pathconf
./mksquashfs.h:217:13: error: call to undeclared function 'pathconf'
./mksquashfs.h:217:27: error: use of undeclared identifier '_PC_PATH_MAX'

Signed-off-by: Anders F Björklund <anders.f.bjorklund@gmail.com>